### ISSUE TITLE
Samplerate is fixed at 48kHz

### ISSUE THREAD

**Issue by stephenhensley** [electro-smith/DaisyDuino#3]

**Comment by andrewikenberry** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Different Samplerates (needs libdaisy Audio Update)](https://trello.com/c/9HDGIYR7/12-different-samplerates-needs-libdaisy-audio-update)

**Comment by stephenhensley** [comment]
fixed in latest updates
