### ISSUE TITLE
Add band-aid for Cache support  

### ISSUE THREAD

**Issue by stephenhensley** [electro-smith/DaisyDuino#4]
For now we can do our `dsy_sdram_init` and `dsy_mpu_init` function in the init. This will at least give us access until we can get a patch with native support baked into the core.

Adding a call to dsy_sdram_init() will be sufficient, and then if there isn't a macro somewhere yet for `DSY_SDRAM_BSS` or similar. We should add that because:

 `float __attribute__((section(".sdram_bss"))) big_array[1024*1024];` 

isn't easy or fun to type.

**Comment by beserge** [comment]
Ongoing issue with SDRAM includes. #9 partially sets up SDRAM.

**Comment by andrewikenberry** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [External SDRAM usage](https://trello.com/c/OXpr0fQT/11-external-sdram-usage)

**Comment by andrewikenberry** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Different Samplerates (needs libdaisy Audio Update)](https://trello.com/c/9HDGIYR7/12-different-samplerates-needs-libdaisy-audio-update)

**Comment by stephenhensley** [comment]
This can be closed. The relevant stuff has been added.

The D-Cache still needs a slight modification to stm32duino variant to work, but that wasn't what this issue was about.
