### ISSUE TITLE
Wrong pin in library vs documentation for PATCH_SM?

### ISSUE THREAD

**Issue by m00dawg** [electro-smith/DaisyDuino#45]
The datasheet for the SM (https://www.electro-smith.com/s/ES_Patch_SM_datasheet_v103.pdf) indicates that the I2C1_SCL pin is PB8 but the define in the library indicates that it is PB7:

https://github.com/electro-smith/DaisyDuino/blob/389ee9540e77e1f3d3294f0a82a6d28bec2f6459/src/daisy_patch_sm.h#L34

**Comment by beserge** [comment]
@m00dawg Good catch! Thanks for the bug report
