### ISSUE TITLE
Support for Arduino 2.0 IDE??

### ISSUE THREAD

**Issue by znmeb** [electro-smith/DaisyDuino#49]
I'm not sure whether this is a bug or a feature request - I want to use DaisyDuino with the Arduino 2.0 IDE. I tried the "blink" example on a Pod the other day. It works fine on the 1.8.19 IDE but on the 2.0.0 RC7 IDE is doesn't. The IDE sees the board when it's running the blinker, but as soon as I put it into bootloader mode to upload the sketch, the IDE reports that the board isn't connected and it won't upload.

I'm guessing this is an issue in the Arduino code and not in the Daisy code, but I don't know how to troubleshoot this. Is there a plan to support the Arduino 2.0.0 IDE?

**Comment by stephenhensley** [comment]
Hi @znmeb, I believe as of 2.0.2 of the Arduino IDE this has been resolved.

Feel free to reopen this if you still have issues.
Thanks for reporting your issue!
