### ISSUE TITLE
Patch SM -- PIN_PATCH_SM_D8 and PIN_PATCH_SM_D9 are reversed

### ISSUE THREAD

**Issue by JDClegg** [electro-smith/DaisyDuino#54]
While trying to integrate an SPI display, discovered that the definitions for D8 and D9 are reversed.

I initialized the Oled with the following:

// the magic incantation
U8G2_SSD1309_128X64_NONAME2_F_4W_SW_SPI oled(U8G2_R0,
                                                                        /* clock=*/ PIN_PATCH_SM_D10,
                                                                         /* data=*/ PIN_PATCH_SM_D8,
                                                                             /* cs=*/ PIN_PATCH_SM_D1,
                                                                             /* dc=*/ PIN_PATCH_SM_D9,
                                                                          /* reset=*/ PIN_PATCH_SM_D3);
I wired it up as follows:

Display Pin Daisy SM Pin
VCC…                A10
GND…               A7
SCK …               D10
SDA …               D9
RES …                D3
DC …                 D8
CS …                  D1

**Comment by stephenhensley** [comment]
Resolved in v1.6.2

Thanks for creating the issue!
